import { v4 as uuidv4 } from "uuid";
export const UserTestimonialData = [
    {
        imgSrc: "https://dakshaknagrale.in/images/about.jpg",
        userComment: "Great Anime!",
        review: "This app is super useful and helpful for users that lack advanced knowledge in photo editing. I liked how user-friendly the app is. I would recommend this app to anyone who is looking for a quick and easy way to crop and edit videos.",
        userName: "Dakshak",
        userDesignation: "Founder & CEO, Aeron Inc.",
        id: uuidv4(),
    },
    {
        imgSrc: "https://dakshaknagrale.in/images/about.jpg",
        userComment: "Great work!",
        review: "This app is super useful and helpful for users that lack advanced knowledge in photo editing. I liked how user-friendly the app is. I would recommend this app to anyone who is looking for a quick and easy way to crop and edit videos.",
        userName: "Dakshak",
        userDesignation: "Founder & CEO, Aeron Inc.",
        id: uuidv4(),
    },
    {
        imgSrc: "https://dakshaknagrale.in/images/about.jpg",
        userComment: "Good Job",
        review: "This app is super useful and helpful for users that lack advanced knowledge in photo editing. I liked how user-friendly the app is. I would recommend this app to anyone who is looking for a quick and easy way to crop and edit videos.",
        userName: "Dakshak",
        userDesignation: "Founder & CEO, Aeron Inc.",
        id: uuidv4(),
    },
    {
        imgSrc: "https://dakshaknagrale.in/images/about.jpg",
        userComment: "Amazing work!",
        review: "This app is super useful and helpful for users that lack advanced knowledge in photo editing. I liked how user-friendly the app is. I would recommend this app to anyone who is looking for a quick and easy way to crop and edit videos.",
        userName: "Dakshak",
        userDesignation: "Founder & CEO, Aeron Inc.",
        id: uuidv4(),
    },
    {
        imgSrc: "https://dakshaknagrale.in/images/about.jpg",
        userComment: "Excellent performance",
        review: "This app is super useful and helpful for users that lack advanced knowledge in photo editing. I liked how user-friendly the app is. I would recommend this app to anyone who is looking for a quick and easy way to crop and edit videos.",
        userName: "Dakshak",
        userDesignation: "Founder & CEO, Aeron Inc.",
        id: uuidv4(),
    },
    {
        imgSrc: "https://dakshaknagrale.in/images/about.jpg",
        userComment: "Excellent performance",
        review: "This app is super useful and helpful for users that lack advanced knowledge in photo editing. I liked how user-friendly the app is. I would recommend this app to anyone who is looking for a quick and easy way to crop and edit videos.",
        userName: "Dakshak",
        userDesignation: "Founder & CEO, Aeron Inc.",
        id: uuidv4(),
    },
];